### ISSUE TITLE
Boost.Python.ArgumentError

### ISSUE THREAD

**Issue by mcarletti** [dougsouza/face-frontalization#19]
Hi,

I got the following error when running the code under the following setup:

Ubuntu 16.04 (4.4.0-97)
Python 2.7.12
OpenCV 3.3.0.10
DLib 19.7.0
SciPy 0.19.0

> Traceback (most recent call last):
  File "demo.py", line 49, in <module>
    demo()
  File "demo.py", line 28, in demo
    lmarks = feature_detection.get_landmarks(img)
  File "~/face-frontalization/facial_feature_detector.py", line 22, in get_landmarks
    predictor = dlib.shape_predictor(predictor_path)
Boost.Python.ArgumentError: Python argument types in
    shape_predictor.\_\_init\_\_(shape_predictor, str)
did not match C++ signature:
    \_\_init\_\_(boost::python::api::object, std::string)
    \_\_init\_\_(_object*)

This is the line 22 of _facial_feature_detector.py_ file:

`predictor = dlib.shape_predictor(predictor_path)`

Any ideas? What should I change to make the code work?
Thank you.

**Comment by dougsouza** [comment]
Hello, 

This looks like an error from dlib itself. Have you tried building dlib from source? Also, check your version of boost python to see if it is supported by dlib. If it doesn't help, I suggest looking for help in their community, they are very helpful.

Cheers,

Douglas
