### ISSUE TITLE
Memory Error 

### ISSUE THREAD

**Issue by haridatascientist** [dougsouza/face-frontalization#2]
Hi,
I run demo.py for a single image. it  worked well

When I run more than 300 images in a loop in windows 32bit it shows the following error
Traceback (most recent call last):
  File "demo.py", line 75, in <module>
    demo()
  File "demo.py", line 57, in demo
    frontal_raw, frontal_sym = frontalize.frontalize(img, proj_matrix, model3D.r
ef_U, eyemask)
  File "C:\Users\Hubino\Downloads\face-frontalization-master\face-frontalization
-master\frontalize.py", line 88, in frontalize
    denominator = weights + weight_take_from_org + weight_take_from_sym
MemoryError

How to avoid the memory error 

Thanks in advance for your valuable help

**Comment by dougsouza** [comment]
Hi @haridatascientist 

As you posted, the line that is throwing the error is: 

`denominator = weights + weight_take_from_org + weight_take_from_sym`

This is a simple Numpy matrix addition which shouldn't be a problem. It seems that you are running out of memory to perform this operation. Are you seeing this error specifically after frontalizing more than 300 images? Are you keeping all those images in memory? I suggest you keep track of your memory usage. One thing you can do is write the image to disk after you frontalize in order to free memory space.

If you want to go further, you can check which Numpy operations are not _inplace_ and optimize the memory usage as they mention here: http://stackoverflow.com/questions/4318615/python-numpy-memoryerror. But I don't think this would solve the problem if you're trying to keep this many images loaded in memory.

Hope it helps!

**Comment by adilalazzawi** [comment]
Hi @dougsouza
I tried to run the code but I got an error

![image](https://cloud.githubusercontent.com/assets/11085328/19295907/4e2030be-8ffd-11e6-9fff-cbef3fad453d.png)

**Comment by adilalazzawi** [comment]
Hi @haridatascientist
could you send me the instruction that you used to run demo().py I tried to run it but i got some errrors
my email is alazzawi1979@gmail.com could you send me the code that you used and the instructions please???
