### ISSUE TITLE
ValueError: array is not broadcastable to correct shape!

### ISSUE THREAD

**Issue by getengqing** [dougsouza/face-frontalization#3]
Hello, I got the error:

frontal_raw[ind_frontal, :] = cv2.remap(img, temp_proj2[0, :].astype('float32'), temp_proj2[1, :].astype('float32'), cv2.INTER_CUBIC)
ValueError: array is not broadcastable to correct shape

what's  the error?How can i sovle?

**Comment by dougsouza** [comment]
Hi @getengqing,

Could you give more details about the error? How are you reading the image? Is it a RGB image? Are having this issue with one image in particular?

**Comment by getengqing** [comment]
I run your demo.py , I have no anyway change to your program. Then got the error!

**Comment by dougsouza** [comment]
That's odd. Which version of OpenCV are you using?

**Comment by 181066** [comment]
Hi, I've got the same error. OpenCV version is 2.4.8

Traceback (most recent call last):
  File "/usr/lib/pycharm/helpers/pydev/pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/lib/pycharm/helpers/pydev/pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/boss/face-frontalization/demo.py", line 48, in <module>
    demo()
  File "/home/boss/face-frontalization/demo.py", line 37, in demo
    frontal_raw, frontal_sym = frontalize.frontalize(img, proj_matrix, model3D.ref_U, eyemask)
  File "/home/boss/face-frontalization/frontalize.py", line 57, in frontalize
    frontal_raw[ind_frontal, :] = cv2.remap(img, temp_proj2[0, :].astype('float32'), temp_proj2[1, :].astype('float32'), cv2.INTER_CUBIC)
ValueError: array is not broadcastable to correct shape

**Comment by dougsouza** [comment]
@181066,

Could you give more details about the input image? It would be great if could share the image itself

**Comment by 181066** [comment]
The input image is the one from your demo - test.jpg
I just run your code without changes. Well, initially I tried to use my image that was looking much more difficult for frontalization. It didn't find facial points and failed. Ok then I just decided to check your demo and got that error.

Thank you.

**Comment by dougsouza** [comment]
Try upgrading your numpy version

**Comment by 181066** [comment]
I have the latest numpy 1.8.2 for ubuntu 14.04.

**Comment by dougsouza** [comment]
@181066, this is the not last version, I am using 1.10.4 on ubuntu 14.04, for example. 

PS.: I am using the [Anaconda](https://www.continuum.io/downloads) python distribution.

**Comment by 181066** [comment]
Thanks a lot. Works fine with Anaconda.

**Comment by zhanlv600** [comment]
I also meet this problem and my numpy version is also 1.8.2.
I just use sudo pip install --upgrade numpy to get latest numpy 1.13.1, and this problem can be solved.
